site:
  title: Updating and Repurposing Red Hat Device Edge Systems with Image Mode for RHEL
  start_page: rhde-bootc-update::index.adoc

content:
  sources:
  - url: ./
  - url: https://github.com/RedHatQuickCourses/rhde-bootc-samples.git

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
