:time_estimate: 8

= Updates to Image Mode Systems

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Update edge devices by using the bootc utility.


WARNING: Pending review

== About transactional updates of image mode systems

Image mode systems are said to apply updates in am atomic and transactional way.
If you are familiar with other transactional systems, such as relational databases, you would expect that image mode systems possess two properties:

1. _Atomicity_: updates are either applied entirely, or not at all.
There is no possible intermediate state, where updates would be only partially applied.

2. _Transactionality_: updates can be undone, or rolled back, cleanly.
You can revert a system completely to the state it was before the update was applied.

These two properties hold true regarding the read-only system image, that is, the contents of its root partition, especially its `/usr` directory, which contains all installed system software, and also regarding its kernel and boot loader.

But they to not apply to mutable system state, that is, to system configurations stored in the `/etc` directory and to application data stored in the `/var` directory.
It may be necessary to provide additional code or processes around bootc updates to ensure the mutable system state ends up in a consistent and working state.

== Bootc update and switch operations

The bootc utility provides two commands related to image mode updates:

Upgrade::
Checks if the current image reference points to a newer bootc container image than the one currently running image.
If it does, then bootc downloads, stages, and deploys the new bootc container image.

Switch::
Changes the image reference and then downloads, stages, and deploys the new bootc container image, if it is different than the currently running image.

Both commands accept the `--apply` option, which immediately reboot after downloading and deploying the new bootc container image.
If you do not specify the `--apply` option, you must reboot manually for the update to take effect.

The concept of "updates" with image mode systems is loosely defined, because there is no constraint that the new bootc container image actually be an update of the currently running image.
It could be a totally unrelated image, which creates interesting possibilities but also some concerns.

Intuitively, you could associate the `bootc upgrade` command with an actual update, because it does not change the image reference, and `bootc switch` with reimaging or repurposing a system, because it changes the image reference.
But consider that the new reference could point to a copy of the same bootc container image in a different OCI container registry.

What users consider the "name" of a container image is actually the name of an image _repository_, which could store multiple, possibly unrelated images, each one identified by its digest.
Red Hat products such as OpenShift and MicroShift do exactly that.
Even the "tag" of a container image is optional.

While a pair of name and tag identifies only one container image at a given moment in time, that pair may refer to different images over time.
This is the concept of a _floating tag_.

So your choice of the `bootc upgrade` or `bootc switch` commands is only dependent on how you organize your container image repositories and how you tag your bootc container images. 
For example, if your organization uses different tags for minor updates, and avoids the use of floating tags, then you must use `bootc switch` to perform all updates.

NOTE: For the remaining of this course, any topic that references the `bootc upgrade` command or an "update" operation also applies to the `bootc switch` command, because they are equivalent for most practical purposes.
Any exceptions will stated be explicitly.

== Updates with private container registries

For a networked update workflow, the bootc utility must connect to an OCI container registry, and that usually requires access credentials.
By default, the bootc utility does NOT share registry configurations with the container tools from RHEL, such as Podman and Skopeo.
That means being able to pull a bootc container image with Podman or inspecting that container image using Skopeo is not sufficient for bootc to be able to perform an update.

Bootc honors the system-wide certificate authority (CA) trust chain, so you do not require configuring bootc with a TLS certificate, and though you can instruct bootc to ignore TLS validation, we strongly recommend that you configure your image mode systems with your internal CA roots.

Bootc stores its registry credentials in the `/etc/ostree/auth.json` file, using the same format as the container tools.
So you can login using Podman or Skopeo and copy the user's registry authentication file to the bootc registry credentials file.

== The bootc update timer service

For the common scenario that organizations use a floating tag to refer to a stream of updates to a bootc container image, image mode systems run an update timer service named `bootc-fetch-apply-updates`.

That timer, managed by Systemd, performs a periodic `bootc upgrade --apply` command.
It enables edge devices, in locations with intermittent network connectivity, to pick updates on their own time.

You may wish to disable the timer, to avoid such automatic updates entirely, or to change it to not reboot immediately, but reboot manually or using a different timer service.
For example, to stage updates during the day, whenever network connectivity is available, but reboot only during a maintenance window.

== System configurations during image updates.

When the bootc utility downloads and applies a new bootc container image, it also performs the deployment process of the bootc container image.
The deployment process extracts the image contents, so it can run in a live system, and builds the overlay file system which becomes the read-only system root directory (`/`). 

The deployment process also initializes a new read-write `/etc` directory, by performing a three-way merge between the contents of the currently running `/etc` directory, the new container image, and the currently running container image.

The tree-way merge process acts on a file-by-file basis, so that new and changed files in the new container image, which didn't exist or changed in the currently running system, are applied to it.
Oh the other hand, any file that changed in the running system is kept as-is, to not override any day-2 configurations already performed to the system.

As the system reboots into the new image, it also switches to the new read-write copy of the `/etc` directory, while the previous copy is retained as part of the old bootc container image deployment.
If any Systemd unit changes files in the `/etc` directory, those changes affect the new read-write copy, which starts to diverge from its bootc container image during its first boot.

Because of the way the three-way merge works, it is recommended that any system configuration which is embedded into a bootc container image, and that is not supposed to be changed at day-2, be performed in the `/usr/lib` directory instead of the `/etc` directory.
Some legacy system services and demons may not support configurations in the `/usr` directory and may require special care during boot updates.

== Application data during image updates.

A bootc update remains using the same copy of the `/var` directory that was already in use by the currently running system.
Bootc updates do NOT change the `/var` directory in anyway.
So, if a new bootc container image includes new content in `/var`, it will NOT be applied by an update.

This means that bootc container images may require Systemd units to run at boot time to initialize data directories, including locations of their temporary and log files.
Applications that abide by currently recommended practices create such directories at run time, instead of assuming they are precreated during package installation, or defers their initialization to Systemd units.

If an update requires migration or conversion of application data to different formats and locations, it also must be performed either manually, after the bootc update operation, or by a Systemd unit embedded in the bootc container image.

IMPORTANT: Scriptlets of RPM packages run during bootc container image build time.
They do NOT run during actual image mode system updates.
Consequently, package updates which work with no further action in package mode may require workarounds to work in image mode.

== What's next

The next lab configures an image mode system to connect to a private registry to apply bootc container image updates, and also demonstrates the effect of such updates on local system configurations and data from applications.
