:time_estimate: 5
:httpd-system-v1-hash-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa: 75391a26d30f30bad03f0741de6c51dff10e7be26199c9b5ceed47019a61b511
:httpd-system-v2-hash-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb: f7b6046dc81cbb80e79bdfb58fcd1c17a3ab84ae47f3b21b1af384f2277d59dc

= Lab: Update Edge Devices from a Container Registry

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Update edge devices, manually and automatically, from new bootc container images published in an OCI container registry.

WARNING: Work in progress

== Before you Begin

You need a _development machine_ running RHEL, to which you have unrestricted sudo access.
The _development machine_ has access to mirrors of RHEL package repositories and bootc container images.

These instructions were tested on RHEL 10.0 but should work with minimal or no changes on newer and older RHEL releases, since 9.6.

If you are using the course classroom, log in on the `workstation` VM as the user `student` with password `student`.
If not, please adapt the instructions to your test environment.

Make sure you verified your test environment by following the xref:ch1-updates:s3-prereqs-lab.adoc[first lab] of this course.

== Instructions

You will perform manual day-2 configurations to an image mode system, to emulate changes that would occur to real systems, and them update that system to a new version of its bootc container image.
After performing the update, you will verify that configuration and application data were preserved by the update.

[ REVIEW PREVIOUS SUMMARY WHEN DONE ]

1. Prepare to start this activity by checking that you have the outcomes from previous activities on your _development machine_.

.. If needed, create a local clone of the sample code repository of this course, but do NOT enter its directory.
Stay on your home directory to start this lab.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *git clone https://github.com/RedHatQuickCourses/rhde-bootc-samples.git*
Cloning into 'rhde-bootc-samples'...
...
--

.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that you have a bootc container image named `httpd-system:v1.0` in your private container registry.
If you do not, please perform the xref:ch1-bib:s3-prereqs-lab.adoc[first lab], which builds and publishes that image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo inspect --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/httpd-system:v1.0*
["v1.0"]
--

.. Verify that you have access to the local VM by using libvirt's session interface.
That VM will be your _test machine_.
+
If you do not, please perform the preparation tasks from the xref:ch1-bib:s3-prereqs-lab.adoc[first lab].
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name               State
-----------------------------------
 -    bootc-iso          shut off
--
+
NOTE: It is fine if you have other local VMs on your system.

.. If your `bootc-iso` VM is not running (like in the output of the previous command), start it.
+
[source,subs="verbatim,quotes"]
--
$ *virsh start bootc-iso*
Domain 'bootc-iso' started
--

2. Access your _test machine_ and perform day-2 configurations, which affect system settings and application data.
+
// Move or repeat some steps to the previous lab, to validate the newly built VM is fine?

.. Enter the `temp-test-iso` directory and access the test system using the SSH key in that directory.
+
// Need the ssh-kegen -R command in the first lab, here it could be left out.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *cd temp-test-iso*
$ *ssh-keygen -R '[127.0.0.1]:8022'*
# Host [127.0.0.1]:8022 found: line 7
/home/student/.ssh/known_hosts updated.
Original contents retained as /home/student/.ssh/known_hosts.old
$ *ssh -i edge-key -p 8022 core@127.0.0.1*
Warning: Permanently added '[127.0.0.1]:8022' (ED25519) to the list of known hosts.
...
[core@bootc-iso ~]$ 
--

.. Record the hash of the current bootc container image of the test system.
+
The password for the `core` user is `redhat123`.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo bootc status*
● Booted image: registry.lab.example.com:5000/httpd-system:v1.0
        Digest: sha256:{httpd-system-v1-hash-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
       Version: 10.0 (2025-09-15 19:03:35.318301268 UTC)
--

.. Verify that the system is configured with UTC as its timezone and change it to reflect local settings.
+
[source,subs="verbatim,quotes"]
--
$ *timedatectl show -p Timezone*
Timezone=UTC
$ *sudo timedatectl set-timezone 'America/Cancun'*
$ *timedatectl show -p Timezone*
Timezone=America/Cancun
--

.. Change the HTML files which mock a single-page web application.
+
[source,subs="verbatim,quotes"]
--
$ *cat /var/www/html/index.html*
Misc tests of bootc images and firewalld
$ *sudo bash -c "echo 'Hacked the webapp' > /var/www/html/index.html"*
$ *curl 127.0.0.1*
Hacked the webapp
--

.. Try to install Cockpit.
+
IMPORTANT: It will fail, but do NOT add the `--transient` option.
+
[source,subs="verbatim,quotes"]
--
$ *rpm -q cockpit*
package cockpit is not installed
$ *sudo yum install cockpit*
...
This bootc system is configured to be read-only. Pass --transient to perform this transaction in a transient overlay which will reset when the system reboots.
Operation aborted.
--

.. Show bootc update service is active, and disable it to ensure you have control of when the system will apply updates.
+
// You may find that the service (not the time) failed, if your VM is running for long enough. It's because the VM has no certs or credentials to access the private registry.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl is-active bootc-fetch-apply-updates.timer*
active
$ *sudo systemctl mask bootc-fetch-apply-updates.timer*
Created symlink '/etc/systemd/system/bootc-fetch-apply-updates.timer' → '/dev/null'.
$ *systemctl is-active bootc-fetch-apply-updates.timer*
failed
--

.. Keep this terminal open, and with the SSH session running, because you will return to it to apply updates.
Open a new terminal on your _development machine_ to proceed with the next step.

3. Build and publish an updated bootc container image.

.. Create a new working directory, copy sample files from git repo, and copy the SSH key from the previous working directory ,
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *mkdir temp-test-update*
$ **cp -r rhde-bootc-samples/httpd-update/* temp-test-update**
$ **cp temp-test-iso/edge-key* temp-test-update**
$ *cd temp-test-update*
--

.. Review the Containerfile for the updated bootc container image.
It makes the following changes:
+
--
... Install and enable the Cockpit service.

... Store the updated single-page web application files in the `/webapp/html` directory.

... Store a placeholder file in the old location for the web application files, the `/var/www/html` directory.
--
+
[source,subs="verbatim,quotes"]
--
include::1@samples:httpd-update:example$Containerfile[]
--

.. If you prefer, you can compare the updated Containerfile with the original one for the `httpd-system` bootc container image.
+
[source,subs="verbatim,quotes"]
--
$ *diff Containerfile ../rhde-bootc-samples/httpd-system*
4c4
<   dnf install -y firewalld httpd cockpit && \
---
>   dnf install -y firewalld httpd && \
...
--

.. Build a new bootc container image and publish it in the private registry using the same tag used for initial provisioning of your _test machine_.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman build -t httpd-system:v1.0.1 .*
...
Successfully tagged localhost/httpd-system:v1.0.1
e1390a4dc788a24e36c7ec2da82784ce4d594665eeed9060802e59c0fcfed6c7
$ *skopeo copy containers-storage:localhost/httpd-system:v1.0.1 docker://registry.lab.example.com:5000/httpd-system:v1.0*
...
Copying config e1390a4dc7 done   | 
Writing manifest to image destination
--

4. Apply the image update.

.. Return to the terminal running an SSH session to your _test machine_ and attempt to check for the availability of updates.
+
.. It is expected to fail, because the _test machine_ was never configured with credentials and a CA root for the private registry.
You can confirm it by attempting to log in using Podman.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc upgrade --check*
ERROR Upgrading: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: pinging container registry registry.lab.example.com:5000: Get "https://registry.lab.example.com:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
$ *sudo podman login -u student -p redhat registry.lab.example.com:5000*
Error: authenticating creds for "registry.lab.example.com:5000": pinging container registry registry.lab.example.com:5000: Get "https://registry.lab.example.com:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
--

.. Copy the CA root from the privage registry, add it to the system's trusted CAs, and try again to log in to the private registry using Podman.
+
[source,subs="verbatim,quotes"]
--
$ *scp student@utility:/opt/registry/certs/domain.crt*
domain.crt
$ *sudo cp domain.crt /etc/pki/ca-trust/source/anchors/*
$ *sudo update-ca-trust*
$ *sudo podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Checking for bootc container image updates still fails because the bootc utility does not share registry access credentials with application containers.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc update --check*
ERROR Upgrading: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: reading manifest v1.0 in registry.lab.example.com:5000/httpd-system: authentication required
--

.. Copy the root credentials file to the location expected by the bootc utility.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp /run/containers/0/auth.json /etc/ostree/auth.json*
--

.. Now it works.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo bootc update --check*
Update available for: docker://registry.lab.example.com:5000/httpd-system:v1.0
  Version: 10.0
  Digest: sha256:{httpd-system-v2-hash-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}
...
--
+
NOTE: If you get an error about "updating mtime", you can safely ignore it.

.. Apply the update, which reboots your _test machine_.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc update --apply*
...
Rebooting system
...
Connection to 127.0.0.1 closed.
--

.. Wait a few moments, to give your _test machine_ time to reboot, and reconnect to it.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-key -p 8022 core@127.0.0.1*
...
[core@bootc-iso ~]$ 
--

5. Verify the side-effects of the update.

.. The new image is the current booted image, and the previous image is still available for rolling back.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo bootc status*
● Booted image: registry.lab.example.com:5000/httpd-system:v1.0
        Digest: sha256:{httpd-system-v2-hash-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}
       Version: 10.0 (2025-09-30 22:54:29.224606481 UTC)

  Rollback image: registry.lab.example.com:5000/httpd-system:v1.0
          Digest: sha256:{httpd-system-v1-hash-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
         Version: 10.0 (2025-09-15 19:03:35.318301268 UTC)
--

.. Clients receive the new web app, proving new /etc from image was applied

.. Old image still on the system (compare hashes with previous steps)

.. Can check for updated (didn't lose credentails for private registry)

.. "moved" index.html is NOT in the system (no changes to /var)

.. Cannot change webapp anymore (it's now read-only)

.. Locale change persists

.. Lorem ipsum

6. Update the test VM (because of cockpit)

.. Show that cockpit is available but cannot access it.

.. Stop the test VM

.. Add a portForward with virt-xml

.. Restart the test VM

.. Show remote access to Cockpit works.

.. Lorem ipsum

Lorem ipsum

== What's Next

.. Lorem ipsum
