:time_estimate: 5

= Troubleshoot Image Mode Systems Using Transient Packages and Toolbx Containers

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Troubleshoot RHEL for edge devices with image mode for RHEL by running tools not included in their system image.

WARNING: Work in progress

== Troubleshooting image mode systems

Image mode systems run Red Hat Enterprise Linux and have a wide range of the tools available from RHEL itself, third-party vendors, and the open source community, to perform troubleshooting.
You could use anything from simple system utilities, such as top, to more sophisticated data collection tools, such as performance co-pilot.

There is always some tension between running a minimal system image, which is faster to provision and update, and presents a smaller attack surface, and running a larger system image which provides a number of troubleshooting tools ready to use, but potentially adding to its vulnerable attack vectors.

With package mode, it is easy to just install any troubleshooting tool the moment you miss it, and then leave it in the system, for the next time you need it.
This is one of the reasons that make systems configuration diverge over time and create maintainability issues, but also one of the factors that make some professionals insecure about adopting image mode for RHEL.

With image mode, you must either include all troubleshooting tools you could ever need on all each and every bootc container image, or learn to live without your preferred tools, right? 
Not true: image mode for RHEL lets you install transient packages using a transient file system overlay.

Package mode also needs the ability of installing troubleshooting tools which do not become a permanent part of a system and do not increase the overhead of managing and maintaining systems.
RHEL has offered an alternative since early 9.x releases, and it supports both package and image mode: toolbx containers.

These two approaches enable you to use a troubleshooting tool, which was not available in a bootc container image, without making permanent changes to a system or to its bootc container image.
In both cases, the troubleshooting tool will be gone when you do not need it anymore, after either a reboot or deleting its toolbx container.

== Using transient overlays

DNF in RHEL 9.6 and 10 is able to install transient packages by creating a read-write overlay over the `/usr` directory.
You just add the `--transient` option to the `dnf install` command.
It works with packages downloads which come from any Yum repository (including Satellite) and also with packages available from local directories.

For packages that comply with the Linux Filesystem Hierarchy Standard (FHS) having a read-write `/usr` directory is sufficient -- they shouldn't be writing to any other directory, except for `/etc` and `/var`, which are mutable in image mode systems.

If you install more transient packages, they share the same read-write overlay.
The read-write overlay is discarded in the next boot, so it is intended for packages you intent to use for a short time.

Transient packages are useful for scenarios such as verifying if a package update fixes an issue, before you build a new bootc container image using the package update.

They are also useful for adding troubleshooting tools which work as system services, for example the https://access.redhat.com/solutions/276533[Sysstat] performance monitoring utilities.
Install the `sysstat` package using `--transient`, start the `sysstat-collect` timer, and let it run for a while, collecting performance data.
When ready, use the `sar` command to generate performance reports.
Or copy the performance data from the `/var/log/sa/` directory to another system and generate the reports there.

== Using toolbx containers

The Toolbx utility was designed to enable developers to run containers that provide sets of development tools seamlessly from their shell.
It does so by running a regular application container, without elevated privileges, but without dropping capabilities which container engines would drop by default.
Toolbx also mounts a series of directories, such as the user home directory and the `/dev` directory, so most tools behave as if they were running directly on the host system instead of in a container.

NOTE: The official name of the project is really _toolbx_ without the "o" of "box".
It was not a typo!
The strange name exists to differentiate from another _toolbox_ open source project, which used to be part of CoreOS and was replaced by the more capable `toolbx` from the Fedora community.

Because toolbx containers do not have complete visibility (and write access) to the host filesystem, there are tasks you cannot run from a toolbx container, such as managing Systemd services.
But for a large number of tools, including tools which require escalating privileges with the `sudo` command, toolbx just works.

You can run the standard toolbx container from your distribution, which in the case of RHEL is an Universal Base Image (UBI) container, and install inside the container any addtional package you need.
That container is not discarded on reboot, but it is retained until you explicitly remove it using Podman.

You can manage multiple toolbx containers, and start or stop each of then at will.
This capability becomes handy once you start creating your own toolbx container images, preconfigured with your preferred troubeshooting tools, and also configuration data for your organization CA root, private package repositories, and private container registries.

For example, your custom toolbx image could specialize in networking troubleshooting tools, including the OpenSSL client utilities, Netstat, and TCPdump.

== Side effects of transient overlays and toolbox containers

After reboot, all packages installed using a transient overay are gone, but any files such packages left in the `/etc` and `/var` directories will still be there.
It is the user responsibility to clean up those files.

Toolbx containers also affect the system's `/var` directory, which in image mode systems include user's home directories in `/var/home`. 
Such changes persist after you remove a toolbx container.
But toolbx containers do not affect the system's `/etc` directory.
Selected files from `/etc` are made available in a toolbx container to ensure it matches its host system users and groups, among other things.

== What's next

The next two activities demonstrate the of transient containers and toolbx containers to run commands not available in a bootc container image, and also demonstrates the side-effects of running those commands on the mutable state of an image mode system.
