:time_estimate: 4

= Update Image Mode Systems in Disconnected Mode

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Update edge devices without reliable network connections to OCI container registries.

WARNING: Pending review

== Using alternate transports with the bootc utility

The bootc ecosystem, which includes the bootc image builder tool, does not provide explicit support for performing disconnected or air-gapped updates of image mode systems, but you can implement such workflows easily by relying on just foundational skills related to Linux container tools.

The bootc utility is configured, by default, to work independently of the Linux container tools, so it doesn't share registry configurations, credentials, and container image layers with Podman and Skopeo.
This enables separation of concerns between teams that manage the operating system and teams that manage applications running on image mode systems.

But bootc shares the underlying libraries which manage container storage and image registries with the Linux container tools, so it inherits from them support for registry mirroring and redirection, multiple image distribution transports, and other features required to implement disconnected update workflows.

You had a glimpse of that in a https://redhatquickcourses.github.io/rhde-bootc-provision/[previous course^], when you inspected a custom installation ISO generated by bootc image builder, and saw that it installs from a bootc container image stored in the installation media itself, instead of from a remote OCI container registry.

In a nutshell, the Linux container tools provide two offline transports for container images:

dir::
Stores an OCI container image alone in a directory.
It preserves the formats of image manifests from older versions of the Docker and OCI specifications, so it guarantees that image digests do not change on the offline copy of the image.

oci::
Stores multiple OCI container images, along with a JSON index, in the same directory.
If those images share layers, an OCI directory stores only one copy of those layers.
It requires using newer versions of the OCI specifications, which brings benefits such as supporting multiple processor architectures, image signatures and artifacts.

The `oci` transport is usually preferred (and the one used by bootc image builder in custom installation ISOs), but your container registry software may not support recent OCI specifications.
If your container registry stores its image manifest using formats from older specifications, using the `oci` transport converts the manifests to a newer format, which changes the image digest and invalidates its image signatures, if any.

Please review the documentation of https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html/building_running_and_managing_containers/working-with-container-images#copying-image-layers-to-a-local-directory[Skopeo], from its manual page, RHEL product docs, or its https://github.com/containers/skopeo[upstream] community docs for more information about how to use Skopeo and the Linux container tools in https://developers.redhat.com/articles/2025/09/24/skopeo-unsung-hero-linux-container-tools[disconnected workflows^].

== Creating offline update media

You can use a custom installation ISO, produced by bootc image builder, to perform offline updates.
You just need to find the location of the bootc container image inside that media, in the `container` directory, and refer to it from a `bootc switch` command.

That approach enables operational technology (OT) teams to carry a single media for both provisioning new devices and updating existing devices, but it creates a media which supports only one system image.
If OT teams must support devices with different purposes, which require different system images, they would need multiple physical medias, one for each kind of device.

Creating a custom installation media is not a quick operation, and the media contains a fully bootable live Linux distribution to run the RHEL installer, which takes considerable disk space.

It is possible, but outside the scope of this course, to create a custom installation media which contains multiple bootc container images, and equip it with a custom grub menu to select the desired image for installation, and then use the same media to perform updates using any of its contained images.

Some teams prefer a quicker workflow, which creates a smaller, update-only media.
It is easy to add multiple additional bootc container images to the same media as the need arises.
You can review an example of such a workflow in a Red Hat Developer https://developers.redhat.com/articles/2025/08/13/deploy-image-mode-update-offline-and-air-gapped-environments[blog post^].

== Offline updates and day-2 customizations

Consider that all of the caveats of networked image mode updates also apply to offline updates: the mutable state stored in the `/etc` and `/var` directories of the system may not be compatible with the packages and software included with the new bootc container image.

A new bootc container image itself may provide Systemd units which handle these issues, or it may require that additional day-2 tasks are performed after applying the update, either manually, or through some automation technology.

== What's next

The next activity, which is the last one in this course, demonstrates how to apply image mode updates in disconnected mode, by using a custom installation media produced by using bootc image builder.
