:time_estimate: 5

= Lab: Update Edge Devices from a Removable Media

_Estimated reading time: *{time_estimate} minutes*._

Objective::
Update edge devices manually from new bootc container images stored in removable media.

WARNING: Work in progress

== Before you Begin

You need a _development machine_ running RHEL, to which you have unrestricted sudo access.
The _development machine_ has access to mirrors of RHEL package repositories and bootc container images.

These instructions were tested on RHEL 10.0 but should work with minimal or no changes on newer and older RHEL releases, since 9.6.

If you are using the course classroom, log in on the `workstation` VM as the user `student` with password `student`.
If not, please adapt the instructions to your test environment.

Make sure you verified your test environment by following the xref:ch1-updates:s3-prereqs-lab.adoc[first lab] of this course.

IMPORTANT: This lab applies the same update as in a ch2-online:s2-update-lab.adoc[previous lab] but using a different method (disconnected vs. connected). If you performed the previous lab, which performs a connected update, it is expected that you also performed its  ch3-rollback-lab.adoc[following lab], which rollbacks that update, so your _test machine_ should be the state it was be before the update, which is the same state as in the end of the first lab.

== Instructions

You will create a removable media image which can be used for both provisioning new systems and updating existing systems, and then you will emulate the usage of the image as removable media in a local VM.

1. Prepare to start this activity by checking that you have the outcomes from previous activities on your _development machine_.

.. Verify that you have a clone of the sample code repository of this course in your home directory.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-bootc-samples/*
LICENSE     bib-cloud-init  bib-qcow2 ...
--

.. If needed, login to your private registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Verify that you have a bootc container image named `httpd-system:v1.0` in your private container registry.
If you do not, please perform the xref:ch1-bib:s3-prereqs-lab.adoc[first lab], which builds and publishes that image.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo inspect --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/httpd-system:v1.0*
["v1.0"]
--

.. Verify that you have access to the local VM which is your _test machine_ by using libvirt's session interface.
That VM will be your _test machine_.
+
If you do not, please perform the preparation tasks from the xref:ch1-updates:s3-prereqs-lab.adoc[first lab].
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name               State
-----------------------------------
 -    bootc-iso          shut off
--
+
NOTE: It is fine if you have other local VMs on your system.

.. If your `bootc-iso` VM is not running (like in the output of the previous command), start it.
+
[source,subs="verbatim,quotes"]
--
$ *virsh start bootc-iso*
Domain 'bootc-iso' started
--

2. Access your _test machine_ and perform day-2 configurations, which affect system settings and application data, to demonstrate that behavior is the same as with online updates.

.. Enter the `temp-test-iso` directory and access your local VM using the SSH key in that directory.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *cd temp-test-iso*
$ *ssh -i edge-key -p 8022 core@127.0.0.1*
Warning: Permanently added '[127.0.0.1]:8022' (ED25519) to the list of known hosts.
...
[core@bootc-iso ~]$ 
--

.. Record the hash of the current bootc container image of the test system.
+
The password for the `core` user is `redhat123`.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo bootc status*
● Booted image: registry.lab.example.com:5000/httpd-system:v1.0
        Digest: sha256:{httpd-system-v1-hash-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
       Version: 10.0 (2025-09-15 19:03:35.318301268 UTC)
--

.. Change the system time zone.
+
[source,subs="verbatim,quotes"]
--
$ *timedatectl show -p Timezone*
Timezone=UTC
$ *sudo timedatectl set-timezone 'Asia/Tokyo'*
$ *timedatectl show -p Timezone*
Timezone=America/Cancun
--

.. Change the HTML files which mock a single-page web application.
+
[source,subs="verbatim,quotes"]
--
$ *cat /var/www/html/index.html*
Misc tests of bootc images and firewalld
$ *sudo bash -c "echo 'Before a disconnected update' > /var/www/html/index.html"*
$ *curl 127.0.0.1*
Before a disconnected update
--

.. Disable the bootc update timer to ensure you have control of when the system will apply updates.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl mask bootc-fetch-apply-updates.timer*
Created symlink '/etc/systemd/system/bootc-fetch-apply-updates.timer' → '/dev/null'.
$ *systemctl is-active bootc-fetch-apply-updates.timer*
failed
--

.. Keep this terminal open, and with the SSH session running, because you will return to it to apply updates.
Open a new terminal on your _development machine_ to proceed with the next step.

3. Build and publish an updated bootc container image.
+
SWITCH TO THE nginx-bootc IMAGE BUT IT MAY NEED TMPFILES.D CONFIGS
+
////
From nginx-core package
/var/lib/nginx
/var/lib/nginx/tmp
/var/log/nginx
/var/log/nginx/access.log
/var/log/nginx/error.log

[root@bootc-iso ~]# ls -lZd /var/lib/nginx
drwxrwx---. 3 nginx root system_u:object_r:httpd_var_lib_t:s0 17 Oct 15 15:10 /var/lib/nginx
[root@bootc-iso ~]# ls -lZd /var/log/nginx
drwx--x--x. 2 root root system_u:object_r:httpd_log_t:s0 41 Oct 15 15:10 /var/log/nginx
[root@bootc-iso ~]# ls -lZ /var/log/nginx
total 8
-rw-r--r--. 1 root root system_u:object_r:httpd_log_t:s0   90 Oct 15 15:11 access.log
-rw-r--r--. 1 root root system_u:object_r:httpd_log_t:s0 2677 Oct 15 15:19 error.log
[root@bootc-iso ~]# ls -lZd /var/lib/nginx/tmp
drwxrwx---. 7 nginx root system_u:object_r:httpd_var_lib_t:s0 78 Oct 15 15:10 /var/lib/nginx/tmp
////

.. Create a new working directory, copy sample files from git repo, and copy the SSH key from the previous working directory.
+
NOTE: If you already performed the previous xref:ch2-online/update-lab[update lab], you have this directory and the new bootc container image ready to go, and can skip to the next step.
If you need more details about the update image, please refer to that lab.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *mkdir temp-test-update*
$ **cp -r rhde-bootc-samples/httpd-update/* temp-test-update**
$ **cp temp-test-iso/edge-key* temp-test-update**
$ *cd temp-test-update*
--

.. Build a new bootc container image and publish it in the private registry using the same floating tag used for initial provisioning of your _test machine_.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman build -t httpd-system:v1.0.1 .*
...
Successfully tagged localhost/httpd-system:v1.0.1
e1390a4dc788a24e36c7ec2da82784ce4d594665eeed9060802e59c0fcfed6c7
$ *skopeo copy containers-storage:localhost/httpd-system:v1.0.1 docker://registry.lab.example.com:5000/httpd-system:v1.0*
...
Copying config e1390a4dc7 done   | 
Writing manifest to image destination
--
+
NOTE: a production workflow would also copy the updated image to a non-floating tag, in the example it would be `1.0.1`.

4. Create an updated installation media.

.. Log in again on your private registry, but this time as the root user.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
--

.. Download the bootc container image to the container storage of the root user.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman pull registry.lab.example.com:5000/httpd-system:v1.0*
...
Writing manifest to image destination
...
--

.. Copy and invoke the script which runs the bootc image builder utility.
+
Be patient, it takes several minutes running.
+
[source,subs="verbatim,quotes"]
--
$ *cp ../temp-test-iso/bib-iso.sh .*
$ *bash bib-iso.sh*
...
Message: Results saved in .
--

.. Copy the installable ISO from the bootc image builder output directory to a more permanent location, and give it an easily identifiable name.
+
[source,subs="verbatim,quotes"]
--
$ *cp output/bootiso/install.iso httpd-system-update.iso*
--

5. Connect the update media on your _test machine_.

.. On your _test machine_, list the disk devices recognized by your local VM.
+
[source,subs="verbatim,quotes"]
--
$ *lsblk *
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sr0     11:0    1  1.8G  0 rom  
vda    252:0    0   20G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0    1G  0 part /boot
└─vda3 252:3    0   19G  0 part /var
                                /sysroot/ostree/deploy/default/var
                                /etc
                                /sysroot
--

.. On your _development machine_, hot-plug a virtual usb disk in your local VM.
+
// MUST BE sdb because the cd-rom device from installation is the sda, though the VM sees it as sr0
+
[source,subs="verbatim,quotes"]
--
$ *virsh attach-disk bootc-iso $PWD/httpd-system.iso sdb --targetbus usb --mode readonly --live*
Disk attached successfully
--

.. Verify that the kernel on your local VM thins a new USB disk was attached.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dmesg | tail*
[17625.346096] usbcore: registered new interface driver uas
[17626.375851] scsi 6:0:0:0: Direct-Access     QEMU     QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[17626.376748] scsi 6:0:0:0: Attached scsi generic sg1 type 0
[17626.389850] sd 6:0:0:0: Power-on or device reset occurred
[17626.392628] sd 6:0:0:0: [sda] 3846408 512-byte logical blocks: (1.97 GB/1.83 GiB)
[17626.393591] sd 6:0:0:0: [sda] Write Protect is on
[17626.393833] sd 6:0:0:0: [sda] Mode Sense: 63 00 80 08
[17626.394500] sd 6:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[17626.664333]  sda: sda1 sda2 sda3
[17626.665089] sd 6:0:0:0: [sda] Attached SCSI disk
--

.. Mount the first partition, which contains the actual installer file system, and verify it contains a bootc continer image in the `containers` directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo mount -o ro /dev/sda1 /var/mnt/*
mount: /var/mnt: WARNING: source write-protected, mounted read-only.
$ *ls /var/mnt/*
EFI  boot  container  images  osbuild-base.ks  osbuild.ks
$ *ls /var/mnt/container/*
blobs  index.json  oci-layout
--

.. When done, you can unplug the virtual USB device.
+
[source,subs="verbatim,quotes"]
--
$ *virsh detach-disk bootc-iso sdb*
Disk detached successfully
--
.. lorem ipsum

6. Apply the disconnected image update.

.. Apply the update, which reboots your _test machine_.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc switch --apply --transport oci /run/LABEL/containers:httpd-system:v1.0*
...
Rebooting system
...
Connection to 127.0.0.1 closed.
--

.. Wait a few moments, to give your _test machine_ time to reboot, and verify that it now runs the updated web application.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *curl 127.0.0.1:8080*
Misc tests of bootc images and firewalld, v1.1
--

.. Reconnect to your _test machine_ so you can verify all changes to the system image, configurations, and data.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-key -p 8022 core@127.0.0.1*
...
[core@bootc-iso ~]$ 
--

7. Verify that changes, from the new image, were applied to your _test machine_, and day-2 changes to configuration and data were retained.

.. Verify that the new image is the current booted image, and the previous image is still available for rolling back.
+
Compare the hashes of each image with your notes from previous steps.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *sudo bootc status*
GRAB OUTPUT
● Booted image: registry.lab.example.com:5000/httpd-system:v1.0
        Digest: sha256:{httpd-system-v2-hash-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}
       Version: 10.0 (2025-09-30 22:54:29.224606481 UTC)

  Rollback image: registry.lab.example.com:5000/httpd-system:v1.0
          Digest: sha256:{httpd-system-v1-hash-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
         Version: 10.0 (2025-09-15 19:03:35.318301268 UTC)
--

.. Verify that the Apache Web Server configurations were changed, and that the web application files are in the `/webapp` directory, proving that changes to `/etc` from the new image were applied.
+
[source,subs="verbatim,quotes"]
--
$ *grep DocumentRoot /etc/httpd/conf/httpd.conf*
# DocumentRoot: The directory out of which you will serve your
DocumentRoot "/webapp/html"
    # access content that does not live under the DocumentRoot.
$ *ls /webapp/html*
index.html
$ *cat /webapp/html/index.html*
Misc tests of bootc images and firewalld, v1.1
--

.. Verify that the changed web application are still in the system, because application data is NOT affected by bootc image upgrades.
+
[source,subs="verbatim,quotes"]
--
$ *ls /var/www/html*
index.html
$ *cat /var/www/html/index.html*
Before a disconnected update
--

.. Verify that you can still check for the availability of bootc image updates, because the system retained the certificate and credentails for acessing the private registry.
+
DOES THIS MAKE SENSE WITH REMOVABLE MEDIA?
+
[source,subs="verbatim,quotes"]
--
$ *sudo bootc upgrade --check*
No changes in: docker://registry.lab.example.com:5000/httpd-system:v1.0
--

.. Verify that the system locale changes were also preserved.
+
[source,subs="verbatim,quotes"]
--
$ *timedatectl show -p Timezone*
Timezone=America/Cancun
--

Lorem ipsum

== What's Next

This was the latest activity of this course.
Stay tuned for new enablement courses for Red Hat Device Edge in the future!
